### ISSUE TITLE
Why Singleton?

### ISSUE THREAD

**Issue by tkj-seasony** [seasony-org/peak_curtis_controller#2]
Why is the singleton needed here: https://github.com/seasony-org/peak_curtis_controller/blob/master/src/mecanum_wheel_math.cpp#L9

Also, there seems to be something off with the includes and the copyright header.

**Comment by mag-seasony** [comment]
The singleton is not needed per say, but this class is purely to perform calculation for the Mecanum equation, and thus should not be reproduced.
This class was copied from the previous controller, as the equations are the same. I did not take the time to clean it up yet.
