### ISSUE TITLE
Why copy shared_ptr

### ISSUE THREAD

**Issue by tkj-seasony** [seasony-org/peak_curtis_controller#4]
Why do you copy the shared_ptr here: https://github.com/seasony-org/peak_curtis_controller/blob/master/src/control_node.cpp#L50
This will increase the ref-count after which you call the destructor of the shared_ptr that you just created, decreasing it again. These are unnecessary operations.

Instead of:
```
    shared_ptr<MobileBaseGroup> mb = static_pointer_cast<MobileBaseGroup>(all_groups_["mobile_base"]);
    mb->setCurrentInputSpeed(msg->linear.x, msg->linear.y, msg->angular.z);
```
You could do:
```
    auto& mb = static_pointer_cast<MobileBaseGroup>(all_groups_["mobile_base"]);
    mb.setCurrentInputSpeed(msg->linear.x, msg->linear.y, msg->angular.z);
```

**Comment by mag-seasony** [comment]
```
    auto& mb = static_pointer_cast<MobileBaseGroup>(all_groups_["mobile_base"]);
    mb.setCurrentInputSpeed(msg->linear.x, msg->linear.y, msg->angular.z);
```
Assigning a pointer to a refference does not work, this is what I changed it to:
`static_pointer_cast<MobileBaseGroup>(all_groups_["mobile_base"])->setCurrentInputSpeed(msg->linear.x, msg->linear.y, msg->angular.z);`

**Comment by tkj-seasony** [comment]
Sorry, I was missing the derefence operator, `*`, in my example. It should be:
```
    auto& mb = *static_pointer_cast<MobileBaseGroup>(all_groups_["mobile_base"]);
    mb.setCurrentInputSpeed(msg->linear.x, msg->linear.y, msg->angular.z);
```
